apiVersion: v1
kind: Service
metadata:
  name: nextjs-svc
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
   - protocol: TCP
     port: 80 # service port
     targetPort: 3000
     nodePort: 30080
